# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tahaschenrechner_sr1.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(401, 726)
        MainWindow.setMinimumSize(QSize(401, 726))
        MainWindow.setMaximumSize(QSize(401, 726))
        MainWindow.setBaseSize(QSize(401, 661))
        icon = QIcon()
        icon.addFile(u":/main/icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"QWidget{ background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/png/tr_blank3.png) }")
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pb_pro = QPushButton(self.centralwidget)
        self.pb_pro.setObjectName(u"pb_pro")
        self.pb_pro.setGeometry(QRect(35, 379, 50, 40))
        self.pb_pro.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/pz_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_p_button.png); border-radius: 100  }")
        self.pb_ko = QPushButton(self.centralwidget)
        self.pb_ko.setObjectName(u"pb_ko")
        self.pb_ko.setGeometry(QRect(173, 622, 50, 40))
        self.pb_ko.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/ko_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_k_button.png); border-radius: 100  }")
        self.pb_0 = QPushButton(self.centralwidget)
        self.pb_0.setObjectName(u"pb_0")
        self.pb_0.setGeometry(QRect(103, 622, 50, 40))
        self.pb_0.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/0_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_0_button.png); border-radius: 100  }")
        self.pb_1 = QPushButton(self.centralwidget)
        self.pb_1.setObjectName(u"pb_1")
        self.pb_1.setGeometry(QRect(103, 562, 50, 40))
        self.pb_1.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/1_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_1_button.png); border-radius: 100  }")
        self.pb_2 = QPushButton(self.centralwidget)
        self.pb_2.setObjectName(u"pb_2")
        self.pb_2.setGeometry(QRect(173, 562, 50, 40))
        self.pb_2.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/2_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_2_button.png); border-radius: 100  }")
        self.pb_3 = QPushButton(self.centralwidget)
        self.pb_3.setObjectName(u"pb_3")
        self.pb_3.setGeometry(QRect(242, 562, 50, 40))
        self.pb_3.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/3_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_3_button.png); border-radius: 100  }")
        self.pb_4 = QPushButton(self.centralwidget)
        self.pb_4.setObjectName(u"pb_4")
        self.pb_4.setGeometry(QRect(104, 501, 50, 40))
        self.pb_4.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/4_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_4_button.png); border-radius: 100  }")
        self.pb_5 = QPushButton(self.centralwidget)
        self.pb_5.setObjectName(u"pb_5")
        self.pb_5.setGeometry(QRect(172, 501, 50, 40))
        self.pb_5.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/5_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_5_button.png); border-radius: 100  }")
        self.pb_6 = QPushButton(self.centralwidget)
        self.pb_6.setObjectName(u"pb_6")
        self.pb_6.setGeometry(QRect(243, 501, 50, 40))
        self.pb_6.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/6_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_6_button.png); border-radius: 100  }")
        self.pb_7 = QPushButton(self.centralwidget)
        self.pb_7.setObjectName(u"pb_7")
        self.pb_7.setGeometry(QRect(103, 441, 50, 40))
        self.pb_7.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/7_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_7_button.png); border-radius: 100  }")
        self.pb_8 = QPushButton(self.centralwidget)
        self.pb_8.setObjectName(u"pb_8")
        self.pb_8.setGeometry(QRect(172, 441, 50, 40))
        self.pb_8.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/8_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_8_button.png); border-radius: 100  }")
        self.pb_9 = QPushButton(self.centralwidget)
        self.pb_9.setObjectName(u"pb_9")
        self.pb_9.setGeometry(QRect(242, 441, 50, 40))
        self.pb_9.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/9_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_9_button.png); border-radius: 100  }")
        self.pb_ig = QPushButton(self.centralwidget)
        self.pb_ig.setObjectName(u"pb_ig")
        self.pb_ig.setGeometry(QRect(103, 318, 50, 40))
        self.pb_ig.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/ig_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_ig_button.png); border-radius: 100  }")
        self.pb_in = QPushButton(self.centralwidget)
        self.pb_in.setObjectName(u"pb_in")
        self.pb_in.setGeometry(QRect(34, 318, 50, 40))
        self.pb_in.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/in_button.png); border-radius: 100  }QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_in_button.png); border-radius: 100  }")
        self.pb_sin = QPushButton(self.centralwidget)
        self.pb_sin.setObjectName(u"pb_sin")
        self.pb_sin.setGeometry(QRect(104, 258, 50, 40))
        self.pb_sin.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/sin_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_sin_button.png); border-radius: 100}")
        self.pb_cos = QPushButton(self.centralwidget)
        self.pb_cos.setObjectName(u"pb_cos")
        self.pb_cos.setGeometry(QRect(172, 258, 50, 40))
        self.pb_cos.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/cos_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_cos_button.png); border-radius: 100}")
        self.pb_tan = QPushButton(self.centralwidget)
        self.pb_tan.setObjectName(u"pb_tan")
        self.pb_tan.setGeometry(QRect(242, 258, 50, 40))
        self.pb_tan.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/tan_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_tan_button.png); border-radius: 100}")
        self.pb_f = QPushButton(self.centralwidget)
        self.pb_f.setObjectName(u"pb_f")
        self.pb_f.setGeometry(QRect(34, 258, 50, 40))
        self.pb_f.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/f_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_f_button.png); border-radius: 100  }")
        self.pb_wur = QPushButton(self.centralwidget)
        self.pb_wur.setObjectName(u"pb_wur")
        self.pb_wur.setGeometry(QRect(103, 379, 50, 40))
        self.pb_wur.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/wur_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_wur_button.png); border-radius: 100  }")
        self.pb_x2 = QPushButton(self.centralwidget)
        self.pb_x2.setObjectName(u"pb_x2")
        self.pb_x2.setGeometry(QRect(172, 379, 50, 40))
        self.pb_x2.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/x2_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_x2_button.png); border-radius: 100  }")
        self.pb_yx = QPushButton(self.centralwidget)
        self.pb_yx.setObjectName(u"pb_yx")
        self.pb_yx.setGeometry(QRect(242, 379, 50, 40))
        self.pb_yx.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/yx_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_yx_button.png); border-radius: 100  }")
        self.pb_1x = QPushButton(self.centralwidget)
        self.pb_1x.setObjectName(u"pb_1x")
        self.pb_1x.setGeometry(QRect(310, 379, 50, 40))
        self.pb_1x.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/1x_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_1x_button.png); border-radius: 100  }")
        self.pb_eex = QPushButton(self.centralwidget)
        self.pb_eex.setObjectName(u"pb_eex")
        self.pb_eex.setGeometry(QRect(35, 441, 50, 40))
        self.pb_eex.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/eex_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_eex_button.png); border-radius: 100  }")
        self.pb_sub = QPushButton(self.centralwidget)
        self.pb_sub.setObjectName(u"pb_sub")
        self.pb_sub.setGeometry(QRect(310, 441, 50, 40))
        self.pb_sub.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/sub_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_sub_button.png); border-radius: 100  }")
        self.pb_pi = QPushButton(self.centralwidget)
        self.pb_pi.setObjectName(u"pb_pi")
        self.pb_pi.setGeometry(QRect(35, 501, 50, 40))
        self.pb_pi.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/pi_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_pi_button.png); border-radius: 100  }")
        self.pb_div = QPushButton(self.centralwidget)
        self.pb_div.setObjectName(u"pb_div")
        self.pb_div.setGeometry(QRect(310, 501, 50, 40))
        self.pb_div.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/div_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_div_button.png); border-radius: 100  }")
        self.pb_vor = QPushButton(self.centralwidget)
        self.pb_vor.setObjectName(u"pb_vor")
        self.pb_vor.setGeometry(QRect(35, 562, 50, 40))
        self.pb_vor.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/vor_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_vor_button.png); border-radius: 100  }")
        self.pb_mul = QPushButton(self.centralwidget)
        self.pb_mul.setObjectName(u"pb_mul")
        self.pb_mul.setGeometry(QRect(310, 562, 50, 40))
        self.pb_mul.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/mul_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_mul_button.png); border-radius: 100  }")
        self.pb_erg = QPushButton(self.centralwidget)
        self.pb_erg.setObjectName(u"pb_erg")
        self.pb_erg.setGeometry(QRect(242, 622, 50, 40))
        self.pb_erg.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/erg_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_erg_button.png); border-radius: 100  }")
        self.pb_ad = QPushButton(self.centralwidget)
        self.pb_ad.setObjectName(u"pb_ad")
        self.pb_ad.setGeometry(QRect(310, 622, 50, 40))
        self.pb_ad.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/ad_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_ad_button.png); border-radius: 100  }")
        self.pb_cec = QPushButton(self.centralwidget)
        self.pb_cec.setObjectName(u"pb_cec")
        self.pb_cec.setGeometry(QRect(35, 622, 50, 40))
        self.pb_cec.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/ce_c_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_cec_button.png); border-radius: 100  }")
        self.pb_mr = QPushButton(self.centralwidget)
        self.pb_mr.setObjectName(u"pb_mr")
        self.pb_mr.setGeometry(QRect(172, 318, 50, 40))
        self.pb_mr.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/mr_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_mr_button.png); border-radius: 100  }")
        self.pb_xm = QPushButton(self.centralwidget)
        self.pb_xm.setObjectName(u"pb_xm")
        self.pb_xm.setGeometry(QRect(242, 318, 50, 40))
        self.pb_xm.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/xm_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_xm_button.png); border-radius: 100  }")
        self.pb_m = QPushButton(self.centralwidget)
        self.pb_m.setObjectName(u"pb_m")
        self.pb_m.setGeometry(QRect(310, 318, 50, 40))
        self.pb_m.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/m_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_m_button.png); border-radius: 100  }")
        self.pb_ka = QPushButton(self.centralwidget)
        self.pb_ka.setObjectName(u"pb_ka")
        self.pb_ka.setGeometry(QRect(310, 258, 20, 40))
        self.pb_ka.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/ka_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_ka_button.png); border-radius: 100}")
        self.pb_kg = QPushButton(self.centralwidget)
        self.pb_kg.setObjectName(u"pb_kg")
        self.pb_kg.setGeometry(QRect(340, 258, 20, 40))
        self.pb_kg.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/kg_button.png); border-radius: 100  } QPushButton:pressed {background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten_p/png/p_kg_button.png); border-radius: 100}")
        self.label2 = QLabel(self.centralwidget)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(43, 58, 316, 36))
        self.label2.setMinimumSize(QSize(316, 36))
        self.label2.setMaximumSize(QSize(316, 36))
        font = QFont()
        font.setFamilies(['Fixedsys 8514oem (Unicode)'])
        font.setPointSize(20)
        self.label2.setFont(font)
        self.label2.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label2.setStyleSheet("""
            QLabel { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/png/lcd_display2.png);
            border-radius: 100;
            color: rgb(42, 65, 65);
            font:'Fixedsys 8514oem (Unicode)';
            font-size: 20px;
            }
        """)
        self.label2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.pb_f_2 = QPushButton(self.centralwidget)
        self.pb_f_2.setObjectName(u"pb_f_2")
        self.pb_f_2.setGeometry(QRect(57, 196, 40, 35))
        self.pb_f_2.setMinimumSize(QSize(40, 35))
        self.pb_f_2.setMaximumSize(QSize(40, 35))
        self.pb_f_2.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/off_switch.png); border-radius: 100  } QPushButton:checked{background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/on_switch.png); border-radius: 100  }")
        self.pb_f_2.setCheckable(True)
        self.pb_f_2.setChecked(False)
        self.pb_f_3 = QPushButton(self.centralwidget)
        self.pb_f_3.setObjectName(u"pb_f_3")
        self.pb_f_3.setGeometry(QRect(285, 196, 60, 35))
        self.pb_f_3.setMinimumSize(QSize(60, 35))
        self.pb_f_3.setMaximumSize(QSize(60, 35))
        self.pb_f_3.setStyleSheet(u"QPushButton { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/deg_switch.png); border-radius: 100  } QPushButton:checked{background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/Tasten/png/grd_switch.png); border-radius: 100  }")
        self.pb_f_3.setCheckable(True)
        self.pb_f_3.setChecked(False)
        self.labellcd = QLabel(self.centralwidget)
        self.labellcd.setObjectName(u"labellcd")
        self.labellcd.setGeometry(QRect(43, 92, 316, 55))
        self.labellcd.setMinimumSize(QSize(316, 55))
        self.labellcd.setMaximumSize(QSize(316, 55))
        font1 = QFont()
        font1.setFamilies(['Fixedsys 8514oem (Unicode)'])
        font1.setPointSize(45)
        font1.setBold(True)
        self.labellcd.setFont(font1)
        self.labellcd.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.labellcd.setStyleSheet("""
            QLabel { background-image: url(C:/Users/sgeld/Pictures/Taschenrechner/Schulrechner_SR1/png/lcd_display2.png);
            border-radius: 100;
            color: rgb(42, 65, 65);
            font:'Fixedsys 8514oem (Unicode)';
            font-size: 45px;
            }
        """)
        self.labellcd.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.AmenuBar = QMenuBar(MainWindow)
        self.AmenuBar.setObjectName(u"AmenuBar")
        self.AmenuBar.setGeometry(QRect(0, 0, 401, 0))
        self.AmenuBar.setMinimumSize(QSize(401, 0))
        self.AmenuBar.setMaximumSize(QSize(401, 0))
        MainWindow.setMenuBar(self.AmenuBar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Tahaschenrechnr", None))
        self.pb_pro.setText("")
        self.pb_ko.setText("")
        self.pb_0.setText("")
        self.pb_1.setText("")
        self.pb_2.setText("")
        self.pb_3.setText("")
        self.pb_4.setText("")
        self.pb_5.setText("")
        self.pb_6.setText("")
        self.pb_7.setText("")
        self.pb_8.setText("")
        self.pb_9.setText("")
        self.pb_ig.setText("")
        self.pb_in.setText("")
        self.pb_sin.setText("")
        self.pb_cos.setText("")
        self.pb_tan.setText("")
        self.pb_f.setText("")
        self.pb_wur.setText("")
        self.pb_x2.setText("")
        self.pb_yx.setText("")
        self.pb_1x.setText("")
        self.pb_eex.setText("")
        self.pb_sub.setText("")
        self.pb_pi.setText("")
        self.pb_div.setText("")
        self.pb_vor.setText("")
        self.pb_mul.setText("")
        self.pb_erg.setText("")
        self.pb_ad.setText("")
        self.pb_cec.setText("")
        self.pb_mr.setText("")
        self.pb_xm.setText("")
        self.pb_m.setText("")
        self.pb_ka.setText("")
        self.pb_kg.setText("")
        self.label2.setText("")
        self.pb_f_2.setText("")
        self.pb_f_3.setText("")
        self.labellcd.setText("")
    # retranslateUi

